### ISSUE TITLE
can u insert the compiled version?

### ISSUE THREAD

**Issue by blademckain** [EitanBlumin/ClrHttpRequest#4]
can u insert also the compiled version?

**Comment by EitanBlumin** [comment]
Good idea!
Yes, I've just published a new version with some improvements, including a compiled DLL and DACPAC files:

https://github.com/EitanBlumin/ClrHttpRequest/releases/tag/v2.0.0

Please note that there's a new SQLCMD Variable called "$(PathToSignedDLL)" which needs to point towards the full path of the compiled DLL file, in order to perform proper assembly signing.

Its default value is `C:\ClrHttpRequest\ClrHttpRequest.dll`
